[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[context.production.environment]
  REACT_APP_API_URL = "your-render-backend-url"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
