services:
  - type: web
    name: recipe-manager-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Marked as sensitive
      - key: SPOONACULAR_API_KEY
        sync: false # Marked as sensitive
